apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: l7-gw-myapis
spec:
  name: l7-gw-myapis
  enabled: true
  endpoint: https://github.com/chuss1/GatewaySoT
  branch: main
  auth:
    type: basic
    existingSecretName: myapis-basic-auth
